---
- hosts: imageservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.2.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # perl
    - command: /home/isucon/.xbuild/perl-install 5.20.2 /home/isucon/.local/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl

- hosts: imageservers
  sudo: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
