---
- hosts: imageservers
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - git:
        repo=https://github.com/isucon/isucon5-qualify.git
        dest=/tmp/isucon5-qualify
    - command: rsync -avz --delete /tmp/isucon5-qualify/webapp /home/isucon/
    # /home/isucon/webapp/{etc,go,java,nodejs,perl,php,python,ruby,scala,sql,static}
    - command: rm -rf /tmp/isucon5-qualify
      args:
        removes: /tmp/isucon5-qualify
    - name: perl
      shell: |
        rm -f cpanfile.snapshot
        PATH=/home/isucon/.local/perl/bin:$PATH carton install
      args:
        chdir: /home/isucon/webapp/perl

  # post_tasks:
    # - command: sudo su - isucon /home/isucon/init.sh

- hosts: imageservers
  sudo: yes
  gather_facts: no
  tasks:
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon mode=644
    - name: perl (systemd)
      copy: src=../files/systemd.perl.service dest=/etc/systemd/system/isuxi.perl.service owner=root mode=644
    # TODO: - nodejs (systemd)

    - name: default application selection
      service: name=isuxi.perl state=running enabled=true
